# Generated by Django 6.0.2 on 2026-02-05 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('allowed_users', models.JSONField(blank=True, default=list, help_text='User IDs allowed. Empty = all users.')),
                ('rate_limit', models.IntegerField(default=100, help_text='Max calls per hour')),
                ('requires_approval', models.BooleanField(default=False)),
                ('blocked_inputs', models.JSONField(blank=True, default=list, help_text='Regex patterns to block')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tool Policies',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('tool', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('execution_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('agent', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('input_summary', models.TextField(blank=True, max_length=500)),
                ('output_summary', models.TextField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('denied', 'Denied'), ('timeout', 'Timeout'), ('pending', 'Pending')], default='success', max_length=20)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'), models.Index(fields=['user_id', 'created_at'], name='core_auditl_user_id_413764_idx'), models.Index(fields=['tool', 'status'], name='core_auditl_tool_9e6791_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('session_summary', models.TextField(blank=True)),
                ('daily_plan', models.JSONField(blank=True, default=dict)),
                ('weekly_plan', models.JSONField(blank=True, default=dict)),
                ('current_task', models.JSONField(blank=True, default=dict)),
                ('raw_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='core_sessio_user_id_9fe768_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('input_data', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='core.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('response_data', models.JSONField(default=dict)),
                ('response_summary', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('partial', 'Partial')], default='success', max_length=20)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='core_toolre_session_ae4e37_idx'), models.Index(fields=['tool_name', 'input_hash'], name='core_toolre_tool_na_758cb2_idx')],
            },
        ),
    ]
