# Generated by Django 6.0.2 on 2026-02-05 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(help_text='User-friendly name of the job', max_length=200)),
                ('cron_expression', models.CharField(help_text='Standard crontab format (* * * * *)', max_length=100)),
                ('task_type', models.CharField(default='tool_execution', max_length=50)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='core_cronjo_user_id_d7b74b_idx')],
            },
        ),
    ]
