# Generated by Django 6.0.2 on 2026-02-05 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cronjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g., person, company, lead', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_id', 'entity_type'], name='core_generi_user_id_00c237_idx'), models.Index(fields=['name'], name='core_generi_name_34083b_idx')],
                'unique_together': {('user_id', 'entity_type', 'name')},
            },
        ),
    ]
