# Generated by Django 6.0.2 on 2026-02-05 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_genericentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('source_type', models.CharField(help_text='e.g., document, contact, task', max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(help_text='e.g., project, company, user', max_length=50)),
                ('target_id', models.CharField(db_index=True, max_length=100)),
                ('relation_type', models.CharField(help_text='e.g., belongs_to, mentioned_in, related_to', max_length=50)),
                ('strength', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'source_id'], name='core_entity_user_id_40e1a3_idx'), models.Index(fields=['user_id', 'target_id'], name='core_entity_user_id_bc576c_idx')],
                'unique_together': {('user_id', 'source_id', 'target_id', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('category', models.CharField(help_text='e.g., travel, software, hosting', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'category'], name='core_financ_user_id_b954b3_idx'), models.Index(fields=['user_id', 'transaction_date'], name='core_financ_user_id_188723_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('url_pattern', models.CharField(blank=True, max_length=2000, null=True)),
                ('frequency', models.CharField(default='daily', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='core_intell_user_id_85aa60_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='core_tasken_user_id_b51ebf_idx'), models.Index(fields=['user_id', 'due_date'], name='core_tasken_user_id_7ab7cf_idx')],
            },
        ),
    ]
