# Generated by Django 6.0.2 on 2026-02-05 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entityrelation_financialentry_intelligencefeed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('tool_names', models.JSONField(default=list, help_text='List of tool names in this skill')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, help_text='Secret for HMAC verification', max_length=255)),
                ('event_types', models.JSONField(default=list, help_text='List of event types to trigger on')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentPlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(related_name='plugins', to='core.agentskill')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('persona', models.TextField()),
                ('voice_profile', models.CharField(default='alloy', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugins', models.ManyToManyField(related_name='agents', to='core.agentplugin')),
                ('skills', models.ManyToManyField(related_name='agents', to='core.agentskill')),
            ],
            options={
                'unique_together': {('user_id', 'name')},
            },
        ),
    ]
