# Generated by Django 6.0.2 on 2026-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agentskill_webhook_agentplugin_customagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customagent',
            name='model_id',
            field=models.CharField(blank=True, help_text='Specific model override for this agent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskentity',
            name='assigned_agent',
            field=models.CharField(blank=True, help_text='Agent responsible for execution', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskentity',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='core.taskentity'),
        ),
        migrations.AddField(
            model_name='taskentity',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='True if managed by Task Engine'),
        ),
        migrations.AddField(
            model_name='taskentity',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Input arguments for automated tasks'),
        ),
        migrations.AddField(
            model_name='taskentity',
            name='result',
            field=models.JSONField(blank=True, default=dict, help_text='Output result of the task'),
        ),
    ]
