# Generated by Django 6.0.2 on 2026-02-06 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('stored_path', models.TextField()),
                ('file_type', models.CharField(db_index=True, max_length=50)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
