"""
Django settings for SecureAssist project.

Generated by 'django-admin startproject' using Django 6.0.2.
Configured for:
- Django 6 built-in background tasks (django.tasks)
- Cron job scheduling
- Multi-agent architecture
"""

import os
from pathlib import Path
import json

# Load secrets from vault if available
vault_path = os.path.expanduser("~/.secureassist/vault.json")
if os.path.exists(vault_path):
    try:
        with open(vault_path, "r") as f:
            secrets = json.load(f)
            for k, v in secrets.items():
                if k not in os.environ: # Don't overwrite existing env vars
                    os.environ[k] = str(v)
    except Exception as e:
        print(f"Warning: Failed to load secrets from vault: {e}")

# Load .env config if available
env_path = Path(__file__).resolve().parent.parent / '.env'
if env_path.exists():
    try:
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    k, v = line.split('=', 1)
                    if k not in os.environ:
                        os.environ[k] = v
    except Exception as e:
        print(f"Warning: Failed to load .env: {e}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-this-in-production')

# Encryption key for secrets (generate with: from cryptography.fernet import Fernet; Fernet.generate_key())
SECRET_ENCRYPTION_KEY = os.environ.get('SECRET_ENCRYPTION_KEY', None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'django_crontab',
    'auditlog',
    
    # Core
    'core.apps.CoreConfig',
    
    # Agents
    'agents.apps.AgentsConfig',
    
    # Feature apps
    'apps.storage.apps.StorageConfig',
    'apps.web_research.apps.WebResearchConfig',
    'apps.communication.apps.CommunicationConfig',
    'apps.ocr.apps.OcrConfig',
    'apps.productivity',
    
    # Integrations
    'integrations.api.apps.ApiConfig',
    'integrations.telegram_bot.apps.TelegramBotConfig',
    'apps.legal.apps.LegalConfig',
]

# Filter missing dynamic apps to avoid startup failures after partial generation
try:
    import importlib.util
    _cleaned_apps = []
    for _app in INSTALLED_APPS:
        _module_path = _app
        if _app.endswith("Config") and "." in _app:
            _module_path = _app.rsplit(".", 1)[0]
        if _app.startswith("apps.") and importlib.util.find_spec(_module_path) is None:
            print(f"Warning: Skipping missing app: {_app}")
            continue
        _cleaned_apps.append(_app)
    INSTALLED_APPS = _cleaned_apps
except Exception as _e:
    print(f"Warning: Failed to validate INSTALLED_APPS: {_e}")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'secureassist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'secureassist.wsgi.application'
ASGI_APPLICATION = 'secureassist.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For production, use PostgreSQL:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'secureassist'),
#         'USER': os.environ.get('DB_USER', 'postgres'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', ''),
#         'HOST': os.environ.get('DB_HOST', 'localhost'),
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }


# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# For production, use Redis:
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }


# Django 6 Background Tasks Configuration
# https://docs.djangoproject.com/en/6.0/topics/tasks/

TASKS = {
    'default': {
        # Development: ImmediateBackend executes tasks synchronously
        'BACKEND': 'django.tasks.backends.ImmediateBackend',
    }
}

# For production, configure a proper task backend:
# TASKS = {
#     'default': {
#         'BACKEND': 'django.tasks.backends.DatabaseBackend',
#         'OPTIONS': {
#             'database': 'default',
#         }
#     }
# }


# Cron Jobs Configuration (django-crontab)
# Add scheduled tasks here
# Format: ('cron_expression', 'path.to.function', 'job_name')

CRONJOBS = [
    # Check for due reminders every minute
    ('* * * * *', 'core.tasks.check_due_reminders', 'check_reminders'),
    
    # Execute scheduled tasks every minute
    ('* * * * *', 'core.tasks.execute_scheduled_tasks', 'execute_scheduled'),
    
    # Run context compression every hour
    ('0 * * * *', 'agents.tasks.compress_old_sessions', 'compress_sessions'),
    
    # Clean up old tool responses daily at midnight
    ('0 0 * * *', 'core.tasks.cleanup_old_responses', 'cleanup_responses'),
    
    # Sync capability registry every 5 minutes (in case of dynamic app loading)
    ('*/5 * * * *', 'core.tasks.sync_capability_registry', 'sync_registry'),
    
    # Daily audit log summary
    ('0 1 * * *', 'core.tasks.generate_audit_summary', 'audit_summary'),
]



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'secureassist.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'agents': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# =============================================================================
# LLM Configuration
# =============================================================================

_llm_orchestrate = os.environ.get('LLM_ORCHESTRATE', 'anthropic/claude-sonnet-4-20250514')
_llm_summarize = os.environ.get('LLM_SUMMARIZE', _llm_orchestrate)
_llm_code = os.environ.get('LLM_CODE', _llm_orchestrate)
_llm_tool = os.environ.get('LLM_TOOL', _llm_orchestrate)
_llm_vision = os.environ.get('LLM_VISION', 'openai/gpt-4o')
_llm_embed = os.environ.get('LLM_EMBED', 'openai/text-embedding-3-small')
_llm_tts = os.environ.get('LLM_TTS', 'openai/tts-1')
_llm_stt = os.environ.get('LLM_STT', 'openai/whisper-1')

LLM_CONFIG = {
    'orchestrate': _llm_orchestrate,
    'summarize': _llm_summarize,
    'code': _llm_code,
    'tool': _llm_tool,
    'vision': _llm_vision,
    'embed': _llm_embed,
    'tts': _llm_tts,
    'stt': _llm_stt,
}


# =============================================================================
# External API Keys (use environment variables in production)
# =============================================================================

TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', None)
TAVILY_API_KEY = os.environ.get('TAVILY_API_KEY', None)
OCR_API_KEY = os.environ.get('OCR_API_KEY', None)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', None)
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', None)


# =============================================================================
# Agent Configuration
# =============================================================================

AGENT_CONFIG = {
    # Maximum context window size for orchestrator
    'max_context_tokens': 128000,
    
    # Number of chat turns to keep in raw form
    'max_raw_turns': 10,
    
    # Session timeout in minutes
    'session_timeout_minutes': 60,
    
    # Default tool timeout in seconds
    'default_tool_timeout': 30,
    
    # Rate limit for tools (per user per hour)
    'default_rate_limit': 100,
}
